fix(isAuthenticated): always check access_token existence
SpoonX/aurelia-authentication pull request #270
Opened 2016-10-11 08:17 UTC by doktordirk

fixes https://github.com/SpoonX/aurelia-authentication/issues/269

2016-10-12 01:30 UTC, lpj145 approved these changes

2016-10-14 06:17 UTC, RWOverdijk requested changes

2016-10-14 06:17 UTC, RWOverdijk commented on src/authService.js
> +        this.updateToken().catch(error => LogManager.getLogger('authentication').warn(error.message));
Please also return error after logging it.

2016-10-14 06:17 UTC, RWOverdijk commented on src/authService.js
> +      this.updateToken().catch(error => LogManager.getLogger('authentication').warn(error.message));
Please also return error after logging it.

2016-10-14 08:09 UTC, doktordirk commented on src/authService.js
> +      this.updateToken().catch(error => LogManager.getLogger('authentication').warn(error.message));
can.t that.s an empty promise hehe

2016-10-14 08:20 UTC, doktordirk commented on src/authService.js
> +        this.updateToken().catch(error => LogManager.getLogger('authentication').warn(error.message));
can.t that.s an empty promise hehe

2016-10-14 08:25 UTC, RWOverdijk approved these changes

2016-10-14 08:27 UTC, merged