expiredRedirect on updateToken
SpoonX/aurelia-authentication pull request #357
Opened 2017-06-27 20:41 UTC by gregleon

Proposed solution to #321 issue

2017-06-28 07:20 UTC, RWOverdijk commented
@gregleon Awesome! :) Would you mind just changing the commit message according to our [contributing guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit) and also change the coding style? I've commented the changes inline.

2017-06-28 07:21 UTC, RWOverdijk requested changes

2017-06-28 07:21 UTC, RWOverdijk commented on src/authService.js
> +          if(this.getAccessToken()){
if (this.getAccessToken()) {

2017-06-28 07:21 UTC, RWOverdijk commented on src/authService.js
> +                this.authentication.resolveUpdateTokenCallstack(this.isAuthenticated());
2 spaces

2017-06-28 07:21 UTC, RWOverdijk commented on src/authService.js
> +          }else{
} else {

2017-06-28 07:21 UTC, RWOverdijk commented on src/authService.js
> +              if (this.config.expiredRedirect) {
Newline before if

2017-06-28 07:21 UTC, RWOverdijk commented on src/authService.js
> +              this.authentication.resolveUpdateTokenCallstack(Promise.reject(new Error('accessToken not found in refreshToken response')));
Newline before

2017-06-28 07:21 UTC, RWOverdijk commented on src/authService.js
> +          if (this.config.expiredRedirect) {
Newline before

2017-06-28 07:21 UTC, RWOverdijk commented on src/authService.js
> +            PLATFORM.location.assign(this.config.expiredRedirect);
Newline before

2017-06-28 07:22 UTC, RWOverdijk commented
**Re: Commit message**

`fix(authService): redirect on refresh token failure when configured to do so`

2017-06-28 08:38 UTC, gregleon reviewed
I think I got all the changes covered in new commit

2017-06-28 11:48 UTC, gregleon reviewed
Done

2017-06-29 07:54 UTC, RWOverdijk approved these changes

2017-06-29 07:54 UTC, RWOverdijk commented
Looks good to me. I'll get this in with the next release :)

2017-06-29 07:54 UTC, merged

2017-06-29 08:13 UTC, RWOverdijk commented
Published!